#pragma once

#include "Engine/SingletonClass/Engine.h"
#include "Engine/SingletonClass/TimeMgr.h"
#include "Engine/SingletonClass/ResourceMgr.h"
#include "Engine/SingletonClass/FbxMgr.h"
#include "Engine/SingletonClass/FmodMgr.h"
#include "Engine/SingletonClass/GUIMgr.h"
#include "Engine/SingletonClass/PhysicsMgr.h"
#include "Engine/SingletonClass/EventMgr.h"
#include "Engine/SingletonClass/InputEventMgr.h"
#include "Engine/SingletonClass/DataMgr.h"
#include "Engine/SingletonClass/RenderTargetMgr.h"
#include "Engine/SingletonClass/QuadTreeMgr.h"

#include "ECS/RenderSystem.h"
#include "ECS/CameraSystem.h"
#include "ECS/SoundSystem.h"
#include "ECS/LightingSystem.h"
#include "ECS/EffectSystem.h"
#include "ECS/MovementSystem.h"

#include "Engine/Scene.h"
#include "Engine/FbxLoader.h"
#include "Engine/StaticObject.h"
#include "Engine/Actor.h"
#include "Engine/Character.h"
#include "Engine/Level.h"
#include "Engine/Log.h"
