#pragma once

#include "Engine/SingletonClass/Engine.h"
#include "Engine/SingletonClass/TimeMgr.h"
#include "Engine/SingletonClass/ResourceMgr.h"
#include "Engine/SingletonClass/FmodMgr.h"
#include "Engine/SingletonClass/GUIMgr.h"
#include "Engine/SingletonClass/PhysicsMgr.h"
#include "Engine/SingletonClass/DataMgr.h"
#include "Engine/SingletonClass/RenderTargetMgr.h"
#include "Engine/SingletonClass/QuadTreeMgr.h"

#include "ECS/RenderSystem.h"
#include "ECS/CameraSystem.h"
#include "ECS/InputSystem.h"
#include "ECS/AnimationSystem.h"
#include "ECS/SoundSystem.h"

#include "Engine/Scene.h"
#include "Engine/FbxLoader.h"
#include "Engine/StaticObject.h"
#include "Engine/Actor.h"
#include "Engine/Level.h"
#include "Engine/Log.h"
#include "Engine/EntryPoint.h"